### ISSUE TITLE
Ask about pre-extracted features for ShanghaiTech

### ISSUE THREAD

**Issue by ALISURE** [fjchange/MIST_VAD#9] opened 2021-07-17 05:14 UTC
According to other issues, I successfully extracted the features of the ShanghaiTech dataset, but I found that it is different from the features you provided. Can you tell me the details of extracting features? It is best to provide the code. Thank you very much.

**Comment by fjchange** [comment] 2021-07-17 06:18
The feature I provided is extracted from the un-finetuned feature extractor. 

As far as I remember, SHT_I3D features are just a transformation of previous works https://github.com/wanboyang/Anomaly_AR_Net_ICME_2020. As for the features of C3D, which are extracted via the code https://github.com/facebookarchive/C3D as CVPR 2018 (Real-world Anomaly Detection in Surveillance Videos) did.

The pre-extracted features here are for the stage1training, but not the features extracted after the finetuned by MIST.

**Comment by ALISURE** [comment] 2021-07-17 07:07
Thanks for your quick response.

After I downloaded the feature from https://github.com/wanboyang/Anomaly_AR_Net_ICME_2020, I found that it is different from the one you provided. May I need to do something to transform? 

In addition, I found that the clip length of SHT_Feats_for_MIL/SHT_I3D.h5 is 12, but the clip length of https://github.com/wanboyang/Anomaly_AR_Net_ICME_2020 is 16.

![image](https://user-images.githubusercontent.com/10307331/126029111-b2ef3040-7ad5-4623-97b6-c0f1cf3af272.png)

**Comment by fjchange** [comment] 2021-07-17 13:40
It seems I upload the wrong file, I will upload the right one then.

**Comment by ALISURE** [comment] 2021-07-17 13:45
Thank you very much. 

In fact, I am more interested in SHT_I3D.h5 with clip length is 12. Can you describe how to obtain this SHT_I3D.h5?

**Comment by fjchange** [comment] 2021-07-17 14:23
The files are updated. 

As for the clip length, I think the clip length selection should be a trade-off between data size and motion description, so just make some trials to using other sampling clip length, likes 12. But here I used 16.

So, I  close the issue as the problem is solved.

**Closed by fjchange** 2021-07-17 14:23 UTC
